version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 0
  labels:
  - 3. to review
  - dependencies
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 0
