filter:
    excluded_paths:
        - 'js/tests/*'
        - 'js/vendor/*'
        - 'vendor/*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 3600 # Timeout in seconds. 60 minutes
        runs: 8
